### ISSUE TITLE
Add prettier to auto format code whenever someone commits

### ISSUE THREAD

**Issue by ameerthehacker** [ameerthehacker/deno-vscode#10]
## Description

* Add **prettier-quick**, **husky** as a dev dependency and use husky to automatically format staged files.
* Add a .prettierrc file to specify the code formatting settings
* Add a .prettierignore file to ignore unwanted directories like node_modules

## Useful links

The complete process is available here https://prettier.io/docs/en/precommit.html

**Comment by vdepatla** [comment]
I will work on this one ..

**Comment by devanSAGA** [comment]
Hi,
Can you please mention the prettier config you want to keep?
Should I keep it to basic configuration ? 
```
{
  "trailingComma": "es5",
  "tabWidth": 4,
  "semi": false,
  "singleQuote": true
}
```

**Comment by ameerthehacker** [comment]
Yes perfect

**Comment by ameerthehacker** [comment]
closing this issue as a PR was made and merged!
