### ISSUE TITLE
Bug: Extension is not working

### ISSUE THREAD

**Issue by NarHakobyan** [ameerthehacker/deno-vscode#2]
Hi Folks, after installing deno, adding it to $PATH, and installing vscode extension, got this error 

![image](https://user-images.githubusercontent.com/1781506/52537432-48aef480-2d80-11e9-8ce2-1048c61457f6.png)

**Comment by ameerthehacker** [comment]
@NarHakobyan can you please try restarting your computer!

**Comment by NarHakobyan** [comment]
@ameerthehacker why am I need to do a restart?

**Comment by ameerthehacker** [comment]
This is just a ritual just to make sure that the PATH variable is updated in all the programs running in the computer which includes vscode!

**Comment by NarHakobyan** [comment]
it's worked, but I have another issue 😄, setting.json file looks like package json

**Comment by ameerthehacker** [comment]
yes, that is a known issue I will push a fix for that by tomorrow! Thanks
