### ISSUE TITLE
Uncaught NotFound: Cannot resolve module "deno" from "{{file}}.ts"

### ISSUE THREAD

**Issue by pothos-dev** [ameerthehacker/deno-vscode#6]
Hi! Thank you for creating this extension.

I am using Deno on Windows and try to get the VSCode integration right.
When I run "deno init" in VSCode, I get my package.json, tsconfig and node_modules set up.

I tried to run the script that is shown in the README, but whenever I `import * as deno from "deno"`, I cannot run the file:

```
$ deno main.ts
Compiling file:///.../main.ts
Uncaught NotFound: Cannot resolve module "deno" from ".../main.ts"
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at maybeThrowError (js/errors.ts:39:15)
    at sendSync (js/dispatch.ts:86:5)
    at fetchModuleMetaData (js/os.ts:73:19)
    at _resolveModule (js/compiler.ts:255:38)
    at resolveModuleNames (js/compiler.ts:486:35)
    at compilerHost.resolveModuleNames (third_party/node_modules/typescript/lib/typescript.js:121106:138)
    at resolveModuleNamesWorker (third_party/node_modules/typescript/lib/typescript.js:88311:127)
    at resolveModuleNamesReusingOldState (third_party/node_modules/typescript/lib/typescript.js:88553:24)
```

When I copy the deno.d.ts file directly into my project folder instead of importing it, then both Autocompletion and running with `deno` works.

**Comment by ameerthehacker** [comment]
@bearbytes can you please share your tsconfig file and check whether you have a .deno directory in your home directory?

**Comment by pothos-dev** [comment]
Here's my tsconfig (generated by `deno init` from the plugin):
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "allowJs": true,
    "checkJs": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noLib": true,
    "pretty": true,
    "resolveJsonModule": true,
    "plugins": [
      {
        "name": "deno_ls_plugin"
      }
    ],
    "target": "esnext",
    "paths": {
      "deno": [
        "..\\..\\..\\..\\.deno/deno.d.ts"
      ],
      "https://*": [
        "..\\..\\..\\..\\.deno/deps/https/*"
      ],
      "http://*": [
        "..\\..\\..\\..\\.deno/deps/http/*"
      ]
    }
  },
  "include": [
    "./**/*.ts"
  ]
}
```

I do have the .deno Folder in Home, and this scripts seems to agree that the file can be found:
```
> const filepath = require('path').join(process.cwd(), "..\\..\\..\\..\\.deno/deno.d.ts")
undefined
> require('fs').existsSync(filepath)
true
```

It seems that deno is not recognizing the path in tsconfig.

On the other hand, it does not need to, since it can work fine without the type definitions.
Maybe we can make VSCode aware of the typings without needing an import of the d.ts-file, which then breaks the deno executable.
It works fine when I have the d.ts file in the directory, so should the plugin just copy it in there on `deno init`?

**Comment by ameerthehacker** [comment]
@bearbytes This is a bug in the windows specific bug in deno-vscode extension. I will push a release fixing this by tmrw

**Comment by ameerthehacker** [comment]
@bearbytes this has been fixed in the latest release, please reopen this issue if you are still facing problems
