### ISSUE TITLE
Deno not find in the path

### ISSUE THREAD

**Issue by senpl** [ameerthehacker/deno-vscode#7]
I got deno installed and in path, it works from integrated terminal.
But after running Ctrl+p deno init i got

> Could not find deno in the path, please ensure that you have installed deno and it is available in the path

>[2019-05-23 14:45:39.385] [exthost] [info] ExtensionService#_doActivateExtension ameerthehacker.deno-vscode {"startup":false,"activationEvent":"onCommand:extension.denoInit"}
[2019-05-23 14:45:39.385] [exthost] [info] ExtensionService#loadCommonJSModule /home/m/.vscode/extensions/ameerthehacker.deno-vscode-0.0.7/out/extension.js

env: ubuntu 18.04
vs code ver:
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-20-generic
deno version:
deno: 0.6.0
v8: 7.6.53
typescript: 3.4.1

**Comment by senpl** [comment]
It happend directly after installation, restart vscode solves this issue still in new vscode restart usually is not needed so it should be mentioned in extension main page.

**Comment by ameerthehacker** [comment]
Hi @senpl as this extension tries to access the environmental variables which may not be updated unless vscode is restarted. If you feel this is to emphasized on the extension page please feel free to create a PR

**Comment by ameerthehacker** [comment]
Closing this issue please feel free to reopen if you have more suggestions
