### ISSUE TITLE
`~/.deno/deps/*` does not exist

### ISSUE THREAD

**Issue by BrunnerLivio** [ameerthehacker/deno-vscode#9]
Thank you for your extension and effort trying to provide a better developer experience working with Deno.

I am having some issues though. I am just getting started with Deno, so this issue may not be directly affiliated with your extension.

I installed deno correctly on my machine:

```
$ deno -v
deno: 0.14.0
v8: 7.7.200
typescript: 3.5.1
```
 and your extension.

When I run `Deno init` in VSCode it successfully bootstraps my project. However, when I tried to import a std module in my `deps.ts` I got the following error:

```
An import path cannot end with a '.ts' extension. Consider importing 'https://deno.land/std@v0.9.0/http/server' instead.
```

`deps.ts`
```ts
export { Server } from "https://deno.land/std@v0.9.0/http/server.ts";
```

When I looked into the generated `tsconfig.json`, I saw the `compilerOptions.paths.https://*` lead to a non-existing path:

```json
{
  "compilerOptions": {
    ...
    "paths": {
      "deno": [
        "../.deno/deno.d.ts"
      ],
      "https://*": [
        "../.deno/deps/https/*"
      ],
      "http://*": [
        "../.deno/deps/http/*"
      ]
    }
  },
}
``` 

In my .deno:
```bash
$ tree ~/.deno
/home/users/MY_USER/.deno
├── bin
│   └── deno
└── deno.d.ts
```

Note that `.deno/deps` does not exist..

**Comment by fletcherist** [comment]
@BrunnerLivio  heya! btw have you tried this?
```ts
import * as deno from 'deno';
```
as for me, i got this: `File '/Users/MY_USER/.deno/deno.d.ts' is not a module.`
as for your issue, i got same result ```An import path cannot end with a '.ts' extension. Consider importing 'https://deno.land/std@v0.9.0/http/server' instead.```

**Comment by ameerthehacker** [comment]
@BrunnerLivio I believe what @fletcherist would just work! also, try restarting your machine and vscode and run your code once in deno so that it can actually download those dependencies and store it in the .deno directory. If you still face any problems, please let me know

**Comment by BrunnerLivio** [comment]
Yup got it working, thanks a lot :) It was an error with my network / certificates. Totally unrelated to this repository.
